export interface TracerRespondent {
  id: number;
  nama: string;
  nim: string;
  prodi: string;
  fakultas: string;
  tahunLulus: number;
  status: "Bekerja" | "Berwirausaha" | "Lanjut Studi" | "Mencari Kerja";
  instansi: string;
  pendapatan: number; // in IDR
  waktuTunggu: number; // in months
  sebelumLulus: boolean;
}

export const TRACER_RESPONDENTS: TracerRespondent[] = [
  {
    id: 1,
    nama: "I Gede Satria Kurniawan",
    nim: "2115051012",
    prodi: "Pendidikan Teknik Informatika",
    fakultas: "Fakultas Teknik dan Kejuruan",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "Google Indonesia (Software Engineer)",
    pendapatan: 25000000,
    waktuTunggu: 1,
    sebelumLulus: true,
  },
  {
    id: 2,
    nama: "Ni Wayan Sasmitha Putri",
    nim: "2115051034",
    prodi: "Sistem Informasi",
    fakultas: "Fakultas Teknik dan Kejuruan",
    tahunLulus: 2025,
    status: "Berwirausaha",
    instansi: "Sasmitha Tech Studio (Digital Agency)",
    pendapatan: 18000000,
    waktuTunggu: 0,
    sebelumLulus: true,
  },
  {
    id: 3,
    nama: "Made Ari Devayana",
    nim: "2113011004",
    prodi: "Pendidikan Matematika",
    fakultas: "Fakultas Matematika dan Ilmu Pengetahuan Alam",
    tahunLulus: 2025,
    status: "Lanjut Studi",
    instansi: "Institut Teknologi Bandung (S2 Sains Komputasi)",
    pendapatan: 0,
    waktuTunggu: 2,
    sebelumLulus: false,
  },
  {
    id: 4,
    nama: "Anak Agung Istri Kirana",
    nim: "2112021025",
    prodi: "Pendidikan Bahasa Inggris",
    fakultas: "Fakultas Bahasa dan Seni",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "Undiksha Singaraja (Asisten Dosen)",
    pendapatan: 45000000,
    waktuTunggu: 3,
    sebelumLulus: false,
  },
  {
    id: 5,
    nama: "Putu Yoga Pratama",
    nim: "2117051120",
    prodi: "Akuntansi",
    fakultas: "Fakultas Ekonomi",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "KPMG Indonesia (Junior Auditor)",
    pendapatan: 9500000,
    waktuTunggu: 1,
    sebelumLulus: false,
  },
  {
    id: 6,
    nama: "Kadek Dwi Handayani",
    nim: "2111031045",
    prodi: "Pendidikan Guru Sekolah Dasar",
    fakultas: "Fakultas Ilmu Pendidikan",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "SD Negeri 1 Singaraja (Guru Kelas)",
    pendapatan: 3800000,
    waktuTunggu: 2,
    sebelumLulus: false,
  },
  {
    id: 7,
    nama: "Ketut Agus Wirawan",
    nim: "2114011012",
    prodi: "Pendidikan Pancasila dan Kewarganegaraan",
    fakultas: "Fakultas Hukum dan Ilmu Sosial",
    tahunLulus: 2025,
    status: "Mencari Kerja",
    instansi: "-",
    pendapatan: 0,
    waktuTunggu: 6,
    sebelumLulus: false,
  },
  {
    id: 8,
    nama: "Luh Made Shanti Dewanthi",
    nim: "2118011002",
    prodi: "Kedokteran",
    fakultas: "Fakultas Kedokteran",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "RSUD Buleleng (Dokter Internship)",
    pendapatan: 6500000,
    waktuTunggu: 0,
    sebelumLulus: true,
  },
  {
    id: 9,
    nama: "Nyoman Tri Buana",
    nim: "2115051056",
    prodi: "Pendidikan Teknik Elektro",
    fakultas: "Fakultas Teknik dan Kejuruan",
    tahunLulus: 2025,
    status: "Berwirausaha",
    instansi: "Buana Solar Panel Specialist (E-commerce & Services)",
    pendapatan: 12000000,
    waktuTunggu: 1,
    sebelumLulus: true,
  },
  {
    id: 10,
    nama: "I Putu Risky Arisandhy",
    nim: "2113021008",
    prodi: "Pendidikan Kimia",
    fakultas: "Fakultas Matematika dan Ilmu Pengetahuan Alam",
    tahunLulus: 2025,
    status: "Lanjut Studi",
    instansi: "Universitas Gadjah Mada (S2 Kimia Analisis)",
    pendapatan: 0,
    waktuTunggu: 4,
    sebelumLulus: false,
  },
  {
    id: 11,
    nama: "Gusti Ayu Mirah Pradnya",
    nim: "2112011030",
    prodi: "Pendidikan Bahasa Bali",
    fakultas: "Fakultas Bahasa dan Seni",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "SMAN 1 Singaraja (Guru Bahasa Daerah)",
    pendapatan: 4000000,
    waktuTunggu: 2,
    sebelumLulus: false,
  },
  {
    id: 12,
    nama: "Komang Adi Permana",
    nim: "2117011045",
    prodi: "Pendidikan Ekonomi",
    fakultas: "Fakultas Ekonomi",
    tahunLulus: 2025,
    status: "Berwirausaha",
    instansi: "Permana Coffee & Roastery Singaraja",
    pendapatan: 15000000,
    waktuTunggu: 0,
    sebelumLulus: true,
  },
  {
    id: 13,
    nama: "Dewi Ayu Maharani",
    nim: "2111011008",
    prodi: "Bimbingan Konseling",
    fakultas: "Fakultas Ilmu Pendidikan",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "SMK Negeri 1 Singaraja (Guru BK)",
    pendapatan: 3800000,
    waktuTunggu: 3,
    sebelumLulus: false,
  },
  {
    id: 14,
    nama: "I Wayan Agus Satya",
    nim: "2114021005",
    prodi: "Pendidikan Sejarah",
    fakultas: "Fakultas Hukum dan Ilmu Sosial",
    tahunLulus: 2025,
    status: "Lanjut Studi",
    instansi: "Universitas Indonesia (S2 Sejarah Budaya)",
    pendapatan: 0,
    waktuTunggu: 5,
    sebelumLulus: false,
  },
  {
    id: 15,
    nama: "Putu Amara Shanti",
    nim: "2118011033",
    prodi: "Kebidanan",
    fakultas: "Fakultas Kedokteran",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "Puskesmas Buleleng I (Bidan Pembantu)",
    pendapatan: 4200000,
    waktuTunggu: 2,
    sebelumLulus: false,
  },
  {
    id: 16,
    nama: "I Gede Bagus Swastika",
    nim: "2115051088",
    prodi: "Sistem Informasi",
    fakultas: "Fakultas Teknik dan Kejuruan",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "Tokopedia (Backend Developer)",
    pendapatan: 18500000,
    waktuTunggu: 1,
    sebelumLulus: true,
  },
  {
    id: 17,
    nama: "Kadek Rian Sastrawan",
    nim: "2113031024",
    prodi: "Pendidikan Biologi",
    fakultas: "Fakultas Matematika dan Ilmu Pengetahuan Alam",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "Balai Taman Nasional Bali Barat (Staff Konservasi)",
    pendapatan: 5500000,
    waktuTunggu: 2,
    sebelumLulus: false,
  },
  {
    id: 18,
    nama: "Made Diah Pramesti",
    nim: "2112031005",
    prodi: "Pendidikan Bahasa Jepang",
    fakultas: "Fakultas Bahasa dan Seni",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "Japan Bali Travel & Tour Guide",
    pendapatan: 7000000,
    waktuTunggu: 1,
    sebelumLulus: false,
  },
  {
    id: 19,
    nama: "Ketut Dedi Hartawan",
    nim: "2117041010",
    prodi: "Manajemen",
    fakultas: "Fakultas Ekonomi",
    tahunLulus: 2025,
    status: "Berwirausaha",
    instansi: "Dedi Digital Agency (Ads Specialist)",
    pendapatan: 10500000,
    waktuTunggu: 0,
    sebelumLulus: true,
  },
  {
    id: 20,
    nama: "Luh Gede Ayu Kartika",
    nim: "2111021002",
    prodi: "Teknologi Pendidikan",
    fakultas: "Fakultas Ilmu Pendidikan",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "Ruangguru (Instructional Designer)",
    pendapatan: 8500000,
    waktuTunggu: 2,
    sebelumLulus: false,
  },
  {
    id: 21,
    nama: "Anak Agung Bagus Mahendra",
    nim: "2114031040",
    prodi: "Ilmu Hukum",
    fakultas: "Fakultas Hukum dan Ilmu Sosial",
    tahunLulus: 2025,
    status: "Bekerja",
    instansi: "Kejaksaan Negeri Buleleng (Legal Assistant)",
    pendapatan: 6200000,
    waktuTunggu: 3,
    sebelumLulus: false,
  },
  {
    id: 22,
    nama: "Ni Putu Citra Lestari",
    nim: "2118011019",
    prodi: "Kedokteran",
    fakultas: "Fakultas Kedokteran",
    tahunLulus: 2025,
    status: "Lanjut Studi",
    instansi: "Universitas Udayana (Spesialis Anak)",
    pendapatan: 0,
    waktuTunggu: 5,
    sebelumLulus: false,
  },
];
